In [1]:
import pandas as pd
import maboss
from sklearn import mixture
from scipy import stats
from  scipy.stats import kurtosis, median_abs_deviation
from unidip.dip import diptst 
import numpy as np
from tqdm import tqdm
import multiprocessing as mp
import time
import os
#import shutil
from datetime import datetime

In [3]:
array = np.arange(0,1,0.25)

In [28]:
a = [np.arange(0,1.01,0.3,),
     np.arange(0,1.01,0.3),
     np.arange(0,1.01,0.3)]

In [29]:

list(product(*(range(lo, hi+1) for lo, hi in a)))

ValueError: too many values to unpack (expected 2)

In [23]:
from itertools import product

n, m = 2, 2

x = product([1,0], repeat = n*m)
x = np.reshape(list(x), (-1,n,m))
print(x)

pd.DataFrame(x)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 0]]

 [[1 1]
  [0 1]]

 [[1 1]
  [0 0]]

 [[1 0]
  [1 1]]

 [[1 0]
  [1 0]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 0]]

 [[0 1]
  [1 1]]

 [[0 1]
  [1 0]]

 [[0 1]
  [0 1]]

 [[0 1]
  [0 0]]

 [[0 0]
  [1 1]]

 [[0 0]
  [1 0]]

 [[0 0]
  [0 1]]

 [[0 0]
  [0 0]]]


ValueError: Must pass 2-d input. shape=(16, 2, 2)

In [68]:
array_1 = np.arange(0,1.01,0.3)
array_2 = np.arange(0,1.01,0.3)
array_3 = np.arange(0,1.01,0.3)


comb_array = np.array(
    np.meshgrid(array_1,array_2,array_3)).T.reshape(-1,3)

input_mtx = pd.DataFrame(comb_array)


In [77]:
input_mtx.loc[0].

0

In [33]:
array = {}
for i in range(0,4):
    array[i] = np.arange(0,1.01,0.3)

In [81]:
test_array = [np.arange(0,1.01,0.3)]*3
comb_array = np.array(
    np.meshgrid(*test_array)).T.reshape(-1,3)

input_mtx = pd.DataFrame(comb_array, 
                         columns = ['test1','test2','test3'])



0.0

In [97]:
len(input_mtx)

64